version: '3.4'

services:
  clientwebapi:
    image: ${DOCKER_REGISTRY-}clientwebapi
    container_name: client-webapi
    build:
      context: .
      dockerfile: Client.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ServiceA__Uri=http://serviceawebapi
      - Jaeger__Endpoint=http://jaeger:14268/api/traces
    ports:
      - 50000:80
      - 50443:443
    depends_on:
      - jaeger
      - serviceawebapi
    networks:
      - tracecontext

  serviceawebapi:
    image: ${DOCKER_REGISTRY-}serviceawebapi
    container_name: servicea-webapi
    build:
      context: .
      dockerfile: ServiceA.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Jaeger__Endpoint=http://jaeger:14268/api/traces
    depends_on:
      - jaeger
    networks:
      - tracecontext

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - tracecontext

networks:
  tracecontext: